{
 "title": "Screep",
 "tags": [ "Screeps" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Game Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "screeps.planc.shard2.gameTime" }
   ]
  },
  {
   "title": "Global Control Level Progress",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "screeps.planc.shard2.gcl" }
   ]
  },
  {
   "title": "CPU Usage & Bucket",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "CPU Usage" }
   ],
   "targets": [
    { "target": "screeps.planc.shard2.cpu" },
    { "target": "screeps.planc.shard2.bucket" }
   ]
  },
  {
   "title": "Global Power Level Progress",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "screeps.planc.shard2.gpl" }
   ]
  },
  {
   "title": "Global Control Level",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "screeps.planc.shard2.gclLevel" }
   ]
  },
  {
   "title": "Global Power Level",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "screeps.planc.shard2.gplLevel" }
   ]
  },
  {
   "title": "W21S33 Resources",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "storage" }
   ],
   "targets": [
    {
     "target": "screeps.planc.shard2.storageW21S33"
    },
    {
     "target": "screeps.planc.shard2.terminalW21S33"
    }
   ]
  },
  {
   "title": "Shard2 Tick Duration (last 10 minutes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Second" }
   ],
   "targets": [
    {
     "target": "screeps.planc.shard2.tickDuration"
    }
   ]
  },
  {
   "title": "Credits & pixels",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Credits" }
   ],
   "targets": [
    { "target": "screeps.planc.shard2.credits" },
    { "target": "screeps.planc.shard2.pixel" }
   ]
  },
  {
   "title": "Game Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "screeps.planc.shard2.gameTime" }
   ]
  }
 ]
}